apiVersion: 1
deleteDatasources:
- name: Loki
  orgId: 1
datasources:
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://dals_srv-loki:3100
  basicAuth: false
  isDefault: false
  editable: true 
