apiVersion: 1
deleteDatasources:
- name: Prometheus
  orgId: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://192.168.1.51:9090
  basicAuth: false
  isDefault: true
  editable: true
