services:
  srv-loki:
    image: m.daocloud.io/docker.io/grafana/loki
    command: 
    - -config.file=/etc/loki/local-config.yaml
    labels:
      service-type: local
      prometheus-job: loki
    ports:
    - target: 3100
      published: 3100
      mode: host # bypass the routing mesh
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
      placement:
        constraints:
        - node.platform.os==linux
        - node.labels.loki==true
    volumes:
    - source: ./config/loki-config.yaml
      target: /etc/loki/local-config.yaml
      type: bind
    - source: ./config/rules-for-log.yaml
      target: /tmp/scratch
      type: bind
    - source: /etc/localtime
      target: /etc/localtime
      type: bind
      read_only: true
