services:
  srv-loki:
    image: registry.iasf/loki:3.5.2
    command: 
    - -config.file=/etc/loki/local-config.yaml
    labels:
      service-type: local
      prometheus-job: loki
    ports:
    - target: 3100
      published: 3100
      mode: host # bypass the routing mesh
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 3G
      placement:
        constraints:
        - node.platform.os==linux
        - node.labels.loki==true
    user: root
    volumes:
    - source: ../../../loki-data
      target: /tmp/loki
      type: bind
    - source: ./config/loki-config.yaml
      target: /etc/loki/local-config.yaml
      type: bind
    - source: ./rules/fake
      target: /tmp/loki/rules/fake
      type: bind
    - source: /etc/localtime
      target: /etc/localtime
      type: bind
      read_only: true
