import os.path
from .IMConsts import TEMPLATE_PATH

#
GlobalServicesList = [
    # name,
    "iocLogServer",
    "cAdvisor",
    "nodeExporter",
    "portainerServer",
    "portainerAgent",
]

#
LocalServicesList = [
    # name,
    "registry",
    "prometheus",
]

#
CustomServicesList = [
    # ('name', '/path/to/compose/file'),
    # To create compose file for programs should be running in swarm managed by IocManager,
    # please refer to the projects files generated by this tool.
    ('hello', os.path.join(TEMPLATE_PATH, 'compose', 'hello.yaml'))
]