#
GlobalServicesList = [
    # name,
    "log",
]

#
LocalServicesList = [
    # ('name', '/path/to/compose/file'),
    # Please refer to those generated by this tool on how to make compose file for running in swarm.
    ('redis', '')
]
