networks:
  hostnet:
    external: true
    name: host
services:
  srv-grafana:
    image: m.daocloud.io/docker.io/grafana/grafana:12.0.1-ubuntu
    networks:
    - hostnet
    labels:
      service-type: local
      prometheus-job: grafana
    deploy:
      mode: global
      resources:
        limits:
          cpus: "1"
          memory: 1G
      placement:
        constraints:
        - node.platform.os==linux
        - node.labels.grafana==true
    volumes:
    - source: ~/grafana-data
      target: /var/lib/grafana
      type: bind
    - source: /etc/localtime
      target: /etc/localtime
      type: bind
      read_only: true

