services:
  srv-grafana:
    image: registry.iasf/grafana:12.0.2-ubuntu
    labels:
      service-type: local
      prometheus-job: grafana
    ports:
    - target: 3000
      published: 3000
      mode: host # bypass the routing mesh
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
      placement:
        constraints:
        - node.platform.os==linux
        - node.labels.grafana==true
    volumes:
    - source: ../../../grafana-data
      target: /var/lib/grafana
      type: bind
    - source: ./dashboards
      target: /etc/grafana/provisioning/dashboards
      type: bind
    - source: ./datasources
      target: /etc/grafana/provisioning/datasources
      type: bind
    - source: /etc/localtime
      target: /etc/localtime
      type: bind
      read_only: true

