name: docker-registry
services:
  srv-registry:
    container_name: "registry"
    image: "registry:2"
    ports: 
#      - "5000:5000"
      - "443:443"
    restart: always
    volumes:
      - type: bind 
        source: ./../../../registry
        target: /var/lib/registry  
      - type: bind 
        source: ./certs
        target: /certs
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/dals_domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/dals_domain.key
