global:
  scrape_interval: 10s 
  scrape_timeout: 8s
  evaluation_interval: 10s 
  external_labels:
    deployment: prometheus@${HOSTNAME}
    
scrape_config_files:
  - ./scrape-config-*.yaml
    
rule_files:
  - ./rules-for-*.yaml

alerting:
  alertmanagers:
    - dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
#      - host: tcp://127.0.0.10:2375
        role: nodes
      relabel_configs:
        - source_labels: [__meta_dockerswarm_node_hostname]
          target_label: instance
          replacement: $1
        - source_labels: [__meta_dockerswarm_node_address]
          target_label: __address__
          replacement: $1:9093
        - source_labels: [__meta_dockerswarm_node_label_alertmanager]
          regex: true
          action: keep
        - source_labels: [__meta_dockerswarm_node_platform_os]
          regex: linux
          action: keep

  
