global:
  scrape_interval: 15s 
  scrape_timeout: 10s
  evaluation_interval: 15s 
  external_labels:
    deployment: ${HOSTNAME}
    
scrape_config_files:
  - ./scrape-config.yaml
    
rule_files:
  - ./rules-for-*.yaml


  
