groups:
  - name: cAdvisor-monitoring
    rules:
      
      # cpu | threshold: 70% of one single core 
      - record: name_service_instance:container_cpu_core_usage_percent:avg5m
        expr: |2
          (sum by (name, container_label_com_docker_swarm_service_name, instance)
          (rate(container_cpu_usage_seconds_total{id!='/'}[5m]))) * 100
          
      - alert: HighContainerCpuCoreUsagePercent
        expr: name_service_instance:container_cpu_core_usage_percent:avg5m > 70
        for: 5m
        keep_firing_for: 1h
        labels:
          severity: warning
          component: container
        annotations:
          summary: "HighContainerCpuCoreUsagePercent for container {{ $labels.name }}"
          description: 
            "Container {{ $labels.name }} running on {{ $labels.instance }} 
            has used {{ $value }}% of one single cpu core(threshold: 70%)."
          
      # memory | threshold: 70% of assigned memory 
      - record: name_service_instance:container_memory_usage_percent
        expr: |2
            (container_memory_working_set_bytes{id!="/"}  
          / on(name, container_label_com_docker_swarm_service_name, instance) 
            container_spec_memory_limit_bytes{id!="/"}) * 100
            
      - alert: HighContainerMemoryUsagePercent
        expr: name_service_instance:container_memory_usage_percent > 70
        for: 5m
        keep_firing_for: 1h
        labels:
          severity: warning
          component: container
        annotations:
          summary: "HighContainerMemoryUsagePercent for container {{ $labels.name }}"
          description: 
            "Container {{ $labels.name }} running on {{ $labels.instance }} 
            has used {{ $value }}% of its memory limit(threshold: 70%)."
      
      # blkio read | threshold: 10 MB/s
      - record: name_service_instance_device:container_blkio_rate_read:avg5m
        expr: |2
          (sum(rate(container_blkio_device_usage_total{id!='/',operation='Read'}[5m]))
          by (name, container_label_com_docker_swarm_service_name, instance, device)) / 1_000

      - alert: HighContainerBlkioRateRead
        expr: name_service_instance_device:container_blkio_rate_read:avg5m > 10_000
        for: 5m
        keep_firing_for: 1h
        labels:
          severity: warning
          component: container
          unit: KB/s
        annotations:
          summary: "HighContainerBlkioRateRead for container {{ $labels.name }}"
          description: 
            "Container {{ $labels.name }} running on {{ $labels.instance }} 
            experienced a Block I/O READ rate of {{ $value }} MB/s on {{ $labels.device }} in past 5 minutes(threshold: 10 MB/s)."
        
      # blkio write | threshold: 10 MB/s
      - record: name_service_instance_device:container_blkio_rate_write:avg5m
        expr: |2
          (sum(rate(container_blkio_device_usage_total{id!='/',operation='Write'}[5m]))
          by (name, container_label_com_docker_swarm_service_name, instance, device)) / 1_000

      - alert: HighContainerBlkioRateWrite
        expr: name_service_instance_device:container_blkio_rate_write:avg5m > 10_000
        for: 5m
        keep_firing_for: 1h
        labels:
          severity: warning
          component: container
          unit: KB/s
        annotations:
          summary: "HighContainerBlkioRateWrite for container {{ $labels.name }}"
          description: 
            "Container {{ $labels.name }} running on {{ $labels.instance }} 
            experienced a Block I/O WRITE rate of {{ $value }} MB/s on {{ $labels.device }} in past 5 minutes(threshold: 10 MB/s)."
           
      # file system usage | threshold: 70% of maximum capacity
      - record: name_service_instance_device:container_fs_usage_percent
        expr: |2
            (container_fs_usage_bytes{id!='/'}
          / on(name, container_label_com_docker_swarm_service_name, instance, device) 
            container_fs_limit_bytes{id!='/'}) * 100

      - alert: HighContainerFileSystemUsagePercent
        expr: name_service_instance_device:container_fs_usage_percent > 70
        for: 5m
        keep_firing_for: 1h
        labels:
          severity: warning
          component: container
        annotations:
          summary: "HighContainerFileSystemUsagePercent for container {{ $labels.name }}"
          description: 
            "Container {{ $labels.name }} running on {{ $labels.instance }} 
            used {{ $value }}% of the file system limit on {{ $labels.device }}(threshold: 70%)."
          
      # file system read | threshold: 10 MB/s
      - record: name_service_instance_device:container_fs_rate_read:avg5m
        expr: |2
          (sum(rate(container_fs_reads_bytes_total{id!='/'}[5m])) 
          by (name, container_label_com_docker_swarm_service_name, instance, device)) / 1_000

      - alert: HighContainerFileSystemRateRead
        expr: name_service_instance_device:container_fs_rate_read:avg5m > 10_000
        for: 5m
        keep_firing_for: 1h
        labels:
          severity: warning
          component: container
          unit: KB/s
        annotations:
          summary: "HighContainerFileSystemRateRead for container {{ $labels.name }}"
          description: 
            "Container {{ $labels.name }} running on {{ $labels.instance }} 
            experienced a File System READ rate of {{ $value }} MB/s on {{ $labels.device }} in past 5 minutes(threshold: 10 MB/s)."
           
      # file system write | threshold: 10 MB/s
      - record: name_service_instance_device:container_fs_rate_write:avg5m
        expr: |2
          (sum(rate(container_fs_writes_bytes_total{id!='/'}[5m])) 
          by (name, container_label_com_docker_swarm_service_name, instance, device)) / 1_000
          
      - alert: HighContainerFileSystemRateWrite
        expr: name_service_instance_device:container_fs_rate_write:avg5m > 10_000
        for: 5m
        keep_firing_for: 1h
        labels:
          severity: warning
          component: container
          unit: KB/s
        annotations:
          summary: "HighContainerFileSystemRateWrite for container {{ $labels.name }}"
          description: 
            "Container {{ $labels.name }} running on {{ $labels.instance }} 
            experienced a File System WRITE rate of {{ $value }} MB/s on {{ $labels.device }} in past 5 minutes(threshold: 10 MB/s)."
         
      # container offline | threshold: 60s lost of heartbeat
      - record: name_service_instance:container_last_beat_seconds
        expr: |2
          sum by (name, container_label_com_docker_swarm_service_name, instance)
          (time() - container_last_seen{id!='/'})
          
      - alert: ContainerOffline
        expr: name_service_instance:container_last_beat_seconds > 60
        keep_firing_for: 1h
        labels:
          severity: info
          component: container
        annotations:
          summary: "ContainerOffline for container {{ $labels.name }}"
          description: 
            "Container {{ $labels.name }} running on {{ $labels.instance }} 
            lost for {{ $value }} s (threshold: 60 s)."
      
      # service offline | threshold: 60s lost of heartbeat
      - record: service:service_last_beat_seconds
        expr: |2
          time() - (max(container_last_seen{id!='/'}) by (container_label_com_docker_swarm_service_name))
          
      - alert: ServiceOffline
        expr: service:service_last_beat_seconds > 60
        keep_firing_for: 1h
        labels:
          severity: critical
          component: service
        annotations:
          summary: "ServiceOffline for {{ $labels.container_label_com_docker_swarm_service_name }}"
          description: 
            "Service {{ $labels.container_label_com_docker_swarm_service_name }} lost for {{ $value }} s (threshold: 60 s)."
            
      # instance service offline | threshold: 60s lost of heartbeat
      - record: instance_service:service_last_beat_seconds
        expr: |2
          time() - (max(container_last_seen{id!='/'}) by (container_label_com_docker_swarm_service_name, instance))
          
      - alert: InstanceServiceOffline
        expr: instance_service:service_last_beat_seconds > 60
        keep_firing_for: 1h
        labels:
          severity: warning
          component: service
        annotations:
          summary: "InstanceServiceOffline for {{ $labels.container_label_com_docker_swarm_service_name }}"
          description: 
            "Service {{ $labels.container_label_com_docker_swarm_service_name }} lost on {{ $labels.instance }} for {{ $value }} s (threshold: 60 s)."
      
      # container network receive rate
      - record: name_service_instance:container_network_kilobytes_rate_receive:avg5m
        expr: |2
          (sum(rate(container_network_receive_bytes_total{id!='/'}[5m])) 
          by (name, container_label_com_docker_swarm_service_name, instance)) / 1_000
          
      # container network transmit rate
      - record: name_service_instance:container_network_kilobytes_rate_transmit:avg5m
        expr: |2
          (sum(rate(container_network_transmit_bytes_total{id!='/'}[5m])) 
          by (name, container_label_com_docker_swarm_service_name, instance)) / 1_000
          
      # container network errors rate | threshold: 10 packets per second
      - record: name_service_instance:container_network_error_rate:avg5m
        expr: |2
          sum by (name, container_label_com_docker_swarm_service_name, instance)
          (rate(container_network_receive_errors_total{id!='/'}[5m]) + rate(container_network_transmit_errors_total{id!='/'}[5m]))
          
      - alert: HighContainerNetworkErrorRate
        expr: name_service_instance:container_network_error_rate:avg5m > 10
        for: 5m
        keep_firing_for: 1h
        labels:
          severity: warning
          component: container
        annotations:
          summary: "HighContainerNetworkErrorRate for container {{ $labels.name }}"
          description: 
            "Container {{ $labels.name }} running on {{ $labels.instance }} 
            experienced a network error rate of {{ $value }} count/s on {{ $labels.device }} in past 5 minutes(threshold: 10 count/s)."
      
      # container network packet drop rate | threshold: 10 packets per second
      - record: name_service_instance:container_network_packet_drop_rate:avg5m
        expr: |2
          sum by (name, container_label_com_docker_swarm_service_name, instance)
          (rate(container_network_receive_packets_dropped_total{id!='/'}[5m]) + rate(container_network_transmit_packets_dropped_total{id!='/'}[5m]))
          
      - alert: HighContainerNetworkPacketDropRate
        expr: name_service_instance:container_network_packet_drop_rate:avg5m > 10
        for: 5m
        keep_firing_for: 1h
        labels:
          severity: warning
          component: container
        annotations:
          summary: "HighContainerNetworkPacketDropRate for container {{ $labels.name }}"
          description: 
            "Container {{ $labels.name }} running on {{ $labels.instance }} 
            experienced a network packet drop rate of {{ $value }} count/s on {{ $labels.device }} in past 5 minutes(threshold: 10 count/s)."
      
      #
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
