groups:
  - name: rules-monitoring
    rules:
    
      # absent for scrape jobs on each instance
      - alert: ScrapeJobDown
        expr: up == 0
        for: 1m
        keep_firing_for: 5m
        labels:
          severity: warning
          component: rule
        annotations:
          summary: "ScrapeJobDown for job {{ $labels.job }} on {{ $labels.instance }}"
          description: 
            "Scrape Job Down for job {{ $labels.job }} running on {{ $labels.instance }}."
            
      # absent for scrape jobs on all instances
      - alert: ScrapeJobLost
        expr: absent(up{job='prometheus'}) == 1
        for: 1m
        keep_firing_for: 5m
        labels:
          severity: critical
          component: rule
        annotations:
          summary: "Scrape Job Lost for prometheus"
          description: 
            "Scrape Job Lost for prometheus."
      
      - alert: ScrapeJobDockerDaemonLost
        expr: absent(up{job='docker-daemon'}) == 1
        for: 1m
        keep_firing_for: 5m
        labels:
          severity: critical
          component: rule
        annotations:
          summary: "Scrape Job Lost for docker-daemon"
          description: 
            "Scrape Job Lost for docker-daemon."      
      
      - alert: ScrapeJobNodeExporterLost
        expr: absent(up{job='node-exporter'}) == 1
        for: 1m
        keep_firing_for: 5m
        labels:
          severity: critical
          component: rule
        annotations:
          summary: "Scrape Job Lost for node-exporter"
          description: 
            "Scrape Job Lost for node-exporter."  
      
      - alert: ScrapeJobCadvisorLost
        expr: absent(up{job='cadvisor-swarm'}) == 1
        for: 1m
        keep_firing_for: 5m
        labels:
          severity: critical
          component: rule
        annotations:
          summary: "Scrape Job Lost for cadvisor-swarm"
          description: 
            "Scrape Job Lost for cadvisor-swarm."  
      #
      
      #
      
      #
