groups:
  - name: rules-monitoring
    rules:
    
      # up
      - alert: ScrapeJobDown
        expr: up == 0
        keep_firing_for: 1h
        labels:
          severity: error
          component: rule
        annotations:
          summary: "ScrapeJobDown for job {{ $labels.job }} on {{ $labels.instance }}"
          description: 
            "ScrapeJobDown for job {{ $labels.job }} on {{ $labels.instance }}."
            
      # absent for scrape jobs on all instances
      - alert: ScrapeJobLost
        expr: up{job='prometheus'} == 0
        for: 3m
        keep_firing_for: 1h
        labels:
          severity: error
          component: rule
        annotations:
          summary: "ScrapeJobLost for job prometheus"
          description: 
            "ScrapeJobDown for job prometheus."
      
      - alert: ScrapeJobDockerDaemonLost
        expr: up{job='docker-daemon'} == 0
        for: 3m
        keep_firing_for: 1h
        labels:
          severity: error
          component: rule
        annotations:
          summary: "ScrapeJobDockerDaemonLost for job docker-daemon"
          description: 
            "ScrapeJobDown for job docker-daemon."      
      
      - alert: ScrapeJobNodeExporterLost
        expr: up{job='node-exporter'} == 0
        for: 3m
        keep_firing_for: 1h
        labels:
          severity: error
          component: rule
        annotations:
          summary: "ScrapeJobNodeExporterLost for job node-exporter"
          description: 
            "ScrapeJobDown for job node-exporter."  
      
      - alert: ScrapeJobCadvisorLost
        expr: up{job='cadvisor-swarm'} == 0
        for: 3m
        keep_firing_for: 1h
        labels:
          severity: error
          component: rule
        annotations:
          summary: "ScrapeJobCadvisorLost for job cadvisor-swarm"
          description: 
            "ScrapeJobDown for job cadvisor-swarm."  
      #
      
      #
      
      #
