groups:
  - name: rules-monitoring
    rules:
    
      # absent for scrape jobs on one instances
      - alert: ScrapeJobDown
        expr: up == 0
        for: 1m
        keep_firing_for: 1h
        labels:
          severity: warning
          component: rule
        annotations:
          summary: "ScrapeJobDown for job {{ $labels.job }} on {{ $labels.instance }}"
          description: 
            "ScrapeJobDown for job {{ $labels.job }} on {{ $labels.instance }}."
            
      # absent for scrape jobs on all instances
      - alert: ScrapeJobLost
        expr: max(up{job='prometheus'}) == 0
        for: 1m
        keep_firing_for: 1h
        labels:
          severity: critical
          component: rule
        annotations:
          summary: "ScrapeJobLost for job prometheus"
          description: 
            "ScrapeJobDown for job prometheus."
      
      - alert: ScrapeJobDockerDaemonLost
        expr: max(up{job='docker-daemon'}) == 0
        for: 1m
        keep_firing_for: 1h
        labels:
          severity: critical
          component: rule
        annotations:
          summary: "ScrapeJobDockerDaemonLost for job docker-daemon"
          description: 
            "ScrapeJobDown for job docker-daemon."      
      
      - alert: ScrapeJobNodeExporterLost
        expr: max(up{job='node-exporter'}) == 0
        for: 1m
        keep_firing_for: 1h
        labels:
          severity: critical
          component: rule
        annotations:
          summary: "ScrapeJobNodeExporterLost for job node-exporter"
          description: 
            "ScrapeJobDown for job node-exporter."  
      
      - alert: ScrapeJobCadvisorLost
        expr: max(up{job='cadvisor-swarm'}) == 0
        for: 1m
        keep_firing_for: 1h
        labels:
          severity: critical
          component: rule
        annotations:
          summary: "ScrapeJobCadvisorLost for job cadvisor-swarm"
          description: 
            "ScrapeJobDown for job cadvisor-swarm."  
      #
      
      #
      
      #
