scrape_configs:

  - job_name: 'scrape-swarm-node'
    dockerswarm_sd_configs:
#      - host: tcp://127.0.0.10:2375
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9323
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
        replacement: $1
      - target_label: job
        replacement: docker-daemon



