scrape_configs:
  
  - job_name: 'scrape-registry'
    dockerswarm_sd_configs:
#      - host: tcp://127.0.0.10:2375
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
        replacement: $1
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:5001
      - source_labels: [__meta_dockerswarm_container_label_prometheus_job]
        regex: registry
        action: keep
      - target_label: job
        replacement: registry
