scrape_configs:

  - job_name: 'scrape-cadvisor'
    dockerswarm_sd_configs:
      - host: tcp://127.0.0.10:2375
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
        replacement: $1
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:8080
      - source_labels: [__meta_dockerswarm_container_label_prometheus_job]
        regex: cadvisor
        action: keep
      - source_labels: [__meta_dockerswarm_container_label_prometheus_job]
        target_label: job
        replacement: $1-swarm
    metric_relabel_configs:
      - source_labels: [container_label_com_docker_stack_namespace]
        target_label: stack
        replacement: $1
      - source_labels: [container_label_com_docker_swarm_service_name]
        target_label: service
        replacement: $1
      - source_labels: [container_label_service_type]
        target_label: service_type
        replacement: $1
      

