scrape_configs:

  - job_name: 'scrape-node-exporter'
    dockerswarm_sd_configs:
#      - host: tcp://127.0.0.10:2375
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
        replacement: $1
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9100
      - source_labels: [__meta_dockerswarm_node_availability]
        regex: drain
        action: drop
      - source_labels: [__meta_dockerswarm_container_label_prometheus_job]
        regex: node_exporter
        action: keep
      - source_labels: [__meta_dockerswarm_container_label_prometheus_job]
        target_label: job
        replacement: node-exporter

