{
 "title": "Container Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "PrometheusSource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Container Ovewview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(swarm_manager_leader)", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(swarm_manager_nodes{state='ready'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(swarm_manager_nodes{state!='ready'}) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(engine_daemon_container_states_containers{state='running'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(swarm_manager_tasks_total{state='running'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum by (instance) (swarm_manager_tasks_total{state=~'orphaned|pending|rejected'}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swarm Application",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{service_type='ioc'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swarm Application",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (service) (container_last_seen{service_type=\"custom\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swarm Application",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (service) (container_last_seen{service_type=~\"global|local\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ALERTS{severity='info'})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{severity='warning'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{severity='critical'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Usage Percentage",
   "type": "timeseries",
   "description": "CPU usage percentage of one single core.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_cpu_core_usage_percent:name_service_instance",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_memory_usage_percent:name_service_instance",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Container File System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Container File System Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "container_fs_rate_read:name_service_instance_device",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container File System Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "container_fs_rate_write:name_service_instance_device",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Container Block I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Container Block I/O Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "container_blkio_rate_read:name_service_instance_device",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Block I/O Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "container_blkio_rate_write:name_service_instance_device",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Container Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Container Network Receive Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "container_network_kilobytes_rate_receive:name_service_instance",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Network Transmit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "container_network_kilobytes_rate_transmit:name_service_instance",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Network Error Packets Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "container_network_error_rate:name_service_instance",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Network Drop Packets Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "container_network_packet_drop_rate:name_service_instance",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}