{
 "title": "Node Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "PrometheusSource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Node Ovewview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "description": "Node CPU average usage percentage over all cores.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_cpu_average_usage_percent:instance",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_memory_usage_percent:instance",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node File System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Node File System Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_file_system_usage_percent:instance_device",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Block I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Node Block I/O Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "node_disk_read_kilobytes_rate:instance_device",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Block I/O Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "node_disk_write_kilobytes_rate:instance_device",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Node Network Receive Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "node_network_receive_kilobytes_rate:instance_device",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Network Transmit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "node_network_transmit_kilobytes_rate:instance_device",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}