import os.path
from .IMConfig import COMPOSE_TEMPLATE_PATH

#
GlobalServicesList = [
    # 'name',
    "iocLogServer",
    "cAdvisor",
    "nodeExporter",
]

#
LocalServicesList = [
    # 'name',
    "registry",
    "prometheus",
    "grafana",
    "portainerServer",
    "portainerAgent",
]

#
CustomServicesList = [
    # ('name', '/path/to/compose/file'),
    # To create compose file for programs should be running in swarm managed by IocManager,
    # please refer to the projects files generated by this tool.
    ('hello', os.path.join(COMPOSE_TEMPLATE_PATH, 'hello.yaml'))
]
