services:
  srv-cadvisor:
    image: m.daocloud.io/gcr.io/cadvisor/cadvisor
    command: -docker_only
    ports:
      - "8080:8080"
    labels:
      prometheus-job: cadvisor
    deploy:
      mode: global
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker:/var/lib/docker:ro

