networks:
  hostnet:
    external: true
    name: host
services:
  srv-prometheus:
    image: m.daocloud.io/docker.io/prom/prometheus:v3.3.1
    networks:
    - hostnet
    labels:
      prometheus-job: prometheus
    deploy:
      mode: global
      resources:
        limits:
          cpus: "1"
          memory: 1G
      placement:
        constraints:
        - node.platform.os==linux
        - node.labels.prometheus==true
    volumes:
#    - source: /var/run/docker.sock
#      target: /var/run/docker.sock
#      type: bind
#      read_only: true
    - source: ./config
      target: /etc/prometheus
      type: bind
      read_only: true
    - source: ~/prometheus-data
      target: /prometheus
      type: bind
    - source: /etc/localtime
      target: /etc/localtime
      type: bind
      read_only: true
    command:
    - "--config.file=/etc/prometheus/prometheus-config.yaml"
    - "--storage.tsdb.path=/prometheus"
