---
- name: set up remote machine environment
  hosts: all
  become: true
  vars:
    for_user: zhu
    ansible_ssh_user: ubuntu
  tasks:
    - name: add user account and set password
      vars:
        pwdhash: "{{ 'testing' | password_hash }}"
      ansible.builtin.user:
        name: "{{ for_user }}"
        shell: /bin/bash
        password: "{{ pwdhash }}"
        password_lock: false
    - ansible.builtin.debug:
        var: pwdhash





