- name: set up ssh connection
  hosts: all
  remote_user: zhu
  vars:
    for_user: zhu
    ansible_ssh_host_key_checking: false
  
  tasks:
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: "{{ for_user }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
