services:
  srv-hello:
    image: m.daocloud.io/docker.io/busybox
    entrypoint: 
    - /bin/sh
    - -c
    - "echo hello; sleep infinity"
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "1"
          memory: 1G
    volumes:
    - /etc/localtime:/etc/localtime:ro
