services:
  srv-hello:
    image: registry.iasf/busybox:1.37.0
    entrypoint: 
    - /bin/sh
    - -c
    - "echo hello; sleep infinity"
    labels:
      service-type: custom
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "1"
          memory: 1G
    volumes:
    - /etc/localtime:/etc/localtime:ro
