services:
  srv-prometheus:
    image: m.daocloud.io/docker.io/prom/prometheus:v3.3.1
    ports:
    - target: 9090
      published: 9090
    labels:
      service-type: local
      prometheus-job: prometheus
    deploy:
      mode: global
      resources:
        limits:
          cpus: "1"
          memory: 1G
      placement:
        constraints:
        - node.platform.os==linux
        - node.labels.prometheus==true
    user: root
    volumes:
    - source: /var/run/docker.sock
      target: /var/run/docker.sock
      type: bind
      read_only: true
    - source: ./config
      target: /etc/prometheus
      type: bind
      read_only: true
    - source: ../../../prometheus-data
      target: /prometheus
      type: bind
    - source: /etc/localtime
      target: /etc/localtime
      type: bind
      read_only: true
    - source: /etc/hostname
      target: /etc/hostname
      type: bind
      read_only: true
    - source: ./scripts/run-prometheus.sh
      target: /run-prometheus.sh
      type: bind
    entrypoint: /run-prometheus.sh
    command:
    - "--config.file=/etc/prometheus/prometheus-config.yaml"
    - "--storage.tsdb.path=/prometheus"
    - "--web.enable-lifecycle"
    - "--web.enable-remote-write-receiver"
