global:
  smtp_from: zhujunhua@mail.iasf.ac.cn
  smtp_smarthost: smtp.qiye.aliyun.com:465
  smtp_auth_username: zhujunhua@mail.iasf.ac.cn
  smtp_auth_password_file: /etc/alertmanager/smtp_password
  smtp_require_tls: false

route:
  group_by: ['...']
  receiver: default-mail
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  routes:
  # for webhook receiver.
  - matchers:
    - alertname=~".*"
    group_by: [severity]
    receiver: default-webhook
    continue: true
    # mute_time_intervals:
    # - all-time
  # for webhook of severity=info 
  - matchers:
    - severity="info"
    group_by: [severity]
    receiver: info-webhook
    continue: true
    # mute_time_intervals:
    # - all-time
  # for log line detection.
  - matchers:
    - component=~"ioc"
    group_by: [component, service, severity]
    receiver: test-mail
    routes:
    - matchers:
      - severity="info"
      mute_time_intervals:
      - all-time
    - matchers:
      - severity="warning"
    - matchers:
      - severity="critical"
      repeat_interval: 30m
  # for container offline or service offline.
  - matchers:
    - alertname=~"ContainerOffline|ServiceOffline|InstanceServiceOffline"
    - component=~"container|service"
    group_by: [alertname, service_type]
    receiver: test-mail
    routes:
    - matchers:
      - severity="info"
      mute_time_intervals:
      - all-time
    - matchers:
      - severity="warning"
    - matchers:
      - severity="critical"
      repeat_interval: 30m
  # for scrape job lost.
  - matchers:
    - component="rule"
    group_by: [alertname]
    receiver: test-mail
    routes:
    - matchers:
      - severity="info"
      mute_time_intervals:
      - all-time
    - matchers:
      - severity="warning"
      receiver: test-mail
    - matchers:
      - severity="critical"
      receiver: test-mail-send-resolve
      repeat_interval: 30m
  # add other routes here.
  #
  # for other performance metrics and severity=info.
  - matchers:
    - severity="info"
    mute_time_intervals:
    - all-time
  # for other performance metrics and severity=waring.
  - matchers:
    - severity="warning"
    group_by: [component, severity, service, service_type]
    receiver: test-mail-send-resolve
  # for other performance metrics and severity=critical.
  - matchers:
    - severity="critical"
    group_by: [component, service, service_type, severity]
    receiver: test-mail-send-resolve
    repeat_interval: 30m

inhibit_rules:
- source_matchers:
  - alertname="ServiceOffline"
  target_matchers:
  - alertname="InstanceServiceOffline"
  equal: [service, component, deployment]
- source_matchers:
  - severity="critical"
  target_matchers:
  - severity="warning"
  equal: [name, alertname, service, instance, component, deployment]

time_intervals:
- name: all-time
  time_intervals:
  - times:
    - start_time: 00:00
      end_time: 24:00

receivers:
- name: default-mail
  email_configs:
  - to: 1728831951@qq.com
- name: test-mail
  email_configs:
  - to: 1728831951@qq.com
- name: test-mail-send-resolve
  email_configs:
  - to: 1728831951@qq.com
    send_resolved: true
- name: default-webhook
  webhook_configs:
  - url: http://192.168.20.170:8081/webhook/prometheus
    send_resolved: false
- name: info-webhook
  webhook_configs:
  - url: http://192.168.1.51:8000/alerts
    send_resolved: false
