global:
  smtp_from: zhujunhua@mail.iasf.ac.cn
  smtp_smarthost: smtp.qiye.aliyun.com:465
  smtp_auth_username: zhujunhua@mail.iasf.ac.cn
  smtp_auth_password_file: /etc/alertmanager/smtp_password
  smtp_require_tls: false
  
route:
  group_by: ['...']
  receiver: default-mail
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 30m
  routes:
  # for container offline or service offline.
  - matchers:
    - alertname=~"ContainerOffline|ServiceOffline|InstanceServiceOffline"
    - component=~"container|service"
    group_by: [alertname, service_type]
    receiver: test-mail
    routes:
    # for severity=info
    - matchers:
      - severity="info"
      mute_time_intervals:
      - all-time
    # for severity!=info
    - matchers:
      - severity="warning"
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 30m
    - matchers:
      - severity="critical"
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 10m
  # for scrape job lost.
  - matchers:
    - component="rule"
    group_by: [alertname]
    receiver: test-mail
    routes:
    # for severity=info
    - matchers: 
      - severity="info"
      mute_time_intervals:
      - all-time
    # for severity=warning
    - matchers:
      - severity="warning"
      receiver: test-mail
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 30m
    # for severity=critical
    - matchers:
      - severity="critical"
      receiver: test-mail-send-resolve
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 10m
  # add other routes here.
  #
  # for other performance metrics and severity=info.
  - matchers: 
    - severity="info"
    mute_time_intervals:
    - all-time
  # for other performance metrics and severity=waring.
  - matchers: 
    - severity="warning"
    group_by: [component, severity, service, service_type]
    receiver: test-mail-send-resolve
    group_wait: 30s
    group_interval: 1m
    repeat_interval: 30m
  # for other performance metrics and severity=critical.
  - matchers: 
    - severity="critical"
    group_by: [component, severity, service, service_type]
    receiver: test-mail-send-resolve
    group_wait: 30s
    group_interval: 1m
    repeat_interval: 10m
      
receivers:
# default receiver of unrecognized alerts
- name: default-mail
  email_configs: 
  - to: 1728831951@qq.com
# default receiver of alerts
- name: test-mail
  email_configs: 
  - to: 1728831951@qq.com
# default receiver of alerts and resolved messages
- name: test-mail-send-resolve
  email_configs: 
  - to: 1728831951@qq.com
    send_resolved: true

time_intervals:
- name: all-time
  time_intervals:
  - times:
    - start_time: 00:00
      end_time: 24:00
