services:
  srv-alloy:
    image: registry.iasf/alloy:v1.9.2
    entrypoint: /run.alloy
    command: 
    - run 
    - --server.http.listen-addr=0.0.0.0:12345 
    - --storage.path=/var/lib/alloy/data 
    - /etc/alloy/config.alloy
    labels:
      service-type: global
      prometheus-job: alloy
    ports:
    - target: 12345
      published: 12345
      mode: host # bypass the routing mesh
    deploy:
      mode: global
      resources:
        limits:
          cpus: "1"
          memory: 1G
      placement:
        constraints:
        - node.platform.os==linux
    volumes:
    - source: ../../../alloy-data
      target: /var/lib/alloy/data
      type: bind
    - source: ./config/run.alloy
      target: /run.alloy
      type: bind
    - source: ./config/config.alloy
      target: /etc/alloy/config.alloy
      type: bind
    - source: /var/run/docker.sock
      target: /var/run/docker.sock
      type: bind
    - source: /etc/localtime
      target: /etc/localtime
      type: bind
      read_only: true
    - source: /etc/hostname
      target: /etc/hostname
      type: bind
      read_only: true
