services:
  srv-iocLogServer:
    ports:
    - target: 7004
      published: 7004
      mode: host # bypass the routing mesh
    labels:
      service-type: global
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
      mode: global
      restart_policy:
        window: 10s
      update_config:
        delay: 10s
        failure_action: rollback
        parallelism: 1
    entrypoint:
    - bash
    - -c
    - export HOSTNAME=$$(cat /etc/hostname);
      . ~/.bash_aliases; 
      date; 
      export EPICS_IOC_LOG_FILE_NAME=/opt/EPICS/RUN/iocLog/$$HOSTNAME.ioc.log; 
      echo export EPICS_IOC_LOG_FILE_NAME=$$EPICS_IOC_LOG_FILE_NAME; 
      echo run iocLogServer...; 
      iocLogServer;
    image: image.dals/base:beta-0.2.2
    tty: true
    volumes:
    - source: ../iocLog
      target: /opt/EPICS/RUN/iocLog
      type: bind
    - read_only: true
      source: /etc/localtime
      target: /etc/localtime
      type: bind
    - read_only: true
      source: /etc/hostname
      target: /etc/hostname
      type: bind
