networks:
  hostnet:
    external: true
    name: host
services:
  srv-alertManager:
    image: m.daocloud.io/docker.io/prom/alertmanager:v0.28.1
    entrypoint: /scripts/start-alertmanager.sh
    command:
    - "--config.file=/etc/alertmanager/alertManager-config.yaml"
    - "--storage.path=/alertmanager"
    - "--enable-feature=utf8-strict-mode"
    labels:
      service-type: local
      prometheus-job: alertmanager
    networks:
    - hostnet
    deploy:
      mode: global
      resources:
        limits:
          cpus: "1"
          memory: 1G
      placement:
        constraints:
        - node.platform.os==linux
        - node.labels.alertmanager==true
    volumes:
    - source: /etc/localtime
      target: /etc/localtime
      type: bind
      read_only: true
    - source: /etc/hostname
      target: /etc/hostname
      type: bind
      read_only: true
    - source: ./scripts
      target: /scripts
      type: bind
      read_only: true
    - source: /var/tmp/IocDock
      target: /var/tmp/IocDock
      type: bind
      read_only: true
    - source: ./config
      target: /etc/alertmanager
      type: bind
      read_only: true
    - source: ../../../alertManager-data
      target: /alertmanager
      type: bind
