services:
  srv-alertManager:
    image: m.daocloud.io/docker.io/prom/alertmanager:v0.28.1
    labels:
      prometheus-job: alertmanager
    ports:
    - target: 9093
      published: 9093
      mode: host # bypass the routing mesh
    deploy:
      mode: global
      resources:
        limits:
          cpus: "1"
          memory: 1G
      placement:
        constraints:
        - node.platform.os==linux
        - node.labels.alertmanager==true
    volumes:
    - source: /etc/localtime
      target: /etc/localtime
      type: bind
      read_only: true
